Акт услуг:
  koef: 0.7
  акт: 1
  заказчик: 1
  исполнитель: 1
Паспорт РФ:
  koef: 0.3
  выдачи: 1
  гор.: 1
  дата: 1
  жен.: 1
  код: 1
  муж.: 1
  паспорт: 1
  подразделение: 1
  пол: 1
  российская: 1
  фамилия: 1
  федерация: 1
Счет:
  koef: 1
  итого: 1
  счет: 1
